package com.hgsoft.security.entity;
// default package
// Generated 2014-3-21 17:03:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.shiro.SecurityUtils;

/**
 * TbAdminLogin generated by hbm2java
 */
public class AdminLogin implements BaseEntity {

	private String id;
	private String userName;
	private Date loginTime;
	private String ip;
	private int status;
	private String remark;
	private String orgId;
	
	//查询条件
	
    private String startQueryDate;//开始时间
	private String endQueryDate;//结束时间
	private Admin operator;
	private String uri;
	private String stationNo;
	private String roadNo; 
	

	public String getStartQueryDate() {
		return startQueryDate;
	}

	public void setStartQueryDate(String startQueryDate) {
		this.startQueryDate = startQueryDate;
	}

	public String getEndQueryDate() {
		return endQueryDate;
	}

	public void setEndQueryDate(String endQueryDate) {
		this.endQueryDate = endQueryDate;
	}

	public Admin getOperator() {
		return (Admin)SecurityUtils.getSubject().getSession().getAttribute("operator");
	}

	public void setOperator(Admin operator) {
		this.operator = operator;
	}

	public String getUri() {
		return "status";
	}

	public void setUri(String uri) {
		this.uri = "status";
	}

	public String getStationNo() {
		return stationNo;
	}

	public void setStationNo(String stationNo) {
		this.stationNo = stationNo;
	}

	public String getRoadNo() {
		return roadNo;
	}

	public void setRoadNo(String roadNo) {
		this.roadNo = roadNo;
	}

	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public AdminLogin() {
	}

	public AdminLogin(Date loginTime, int status) {
		this.loginTime = loginTime;
		this.status = status;
	}

	public AdminLogin(String userName, Date loginTime, String ip, int status,
			String remark) {
		this.userName = userName;
		this.loginTime = loginTime;
		this.ip = ip;
		this.status = status;
		this.remark = remark;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
 
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Date getLoginTime() {
		return loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
